/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class davide_jni_HalloFromC */

#ifndef _Included_davide_jni_HalloFromC
#define _Included_davide_jni_HalloFromC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     davide_jni_HalloFromC
 * Method:    print
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_davide_jni_HalloFromC_print
  (JNIEnv *, jobject, jint);

/*
 * Class:     davide_jni_HalloFromC
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_davide_jni_HalloFromC_sum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
